name: Run phpstan

on:
  pull_request:
    branches:
      - develop

jobs:
  phpstan:
    name: 'Run phpstan in PHP ${{ matrix.phpVersion }} | Shopware ${{ matrix.shopwareVersion }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        phpVersion: [ '8.3', '8.4' ]
        shopwareVersion: [ 'v6.7.1.0', 'trunk' ]

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v6
        with:
          path: custom/plugins/${{ github.event.repository.name }}

      - name: 'Allow insecure packages for fixed Shopware versions'
        if: matrix.shopwareVersion != 'trunk'
        shell: bash
        run: |
          mkdir -p ~/.config/composer
          printf '%s\n' '{"config":{"audit":{"block-insecure":false}}}' > ~/.config/composer/config.json

      - name: 'Setup Shopware and Extension'
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          phpVersion: ${{ matrix.phpVersion }}
          shopwareVersion: ${{ matrix.shopwareVersion }}
          install: true
          env: test
          keep-composer-tools: true

      - name: Install dependencies
        run: composer require --dev shopwarelabs/phpstan-shopware

      - name: 'Run phpstan'
        working-directory: custom/plugins/${{ github.event.repository.name }}
        shell: bash
        run: |
          cp phpstan.neon.dist ../../../
          ../../../vendor/bin/phpstan
