name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Netlogix Release Bot
    outputs:
      release_bot_token: ${{ steps.release-bot-app-token.outputs.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v3
        id: release-bot-app-token
        with:
          client-id: ${{ vars.RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        id: semantic   # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ steps.release-bot-app-token.outputs.token }}

  sync-to-develop:
    needs: release
    permissions:
      contents: write
    uses: ./.github/workflows/release_sync.yml
    with:
      release_bot_token: ${{ needs.release.outputs.release_bot_token }}
