name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  phpunit:
    name: 'PHP ${{ matrix.phpVersion }} | Shopware ${{ matrix.shopwareVersion }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        phpVersion: ['8.3', '8.4']
        shopwareVersion: ['v6.7.1.0']

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v6
        with:
          path: custom/plugins/${{ github.event.repository.name }}

      - name: 'Setup Shopware and Extension'
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: ${{ github.event.repository.name }}
          phpVersion: ${{ matrix.phpVersion }}
          shopwareVersion: ${{ matrix.shopwareVersion }}
          install: false
          env: test
          keep-composer-tools: true
          allow-insecure-versions: true

      - name: 'Validate composer.json and composer.lock'
        working-directory: custom/plugins/${{ github.event.repository.name }}
        shell: bash
        run: composer validate

      - name: 'Run Unit Tests'
        working-directory: custom/plugins/${{ github.event.repository.name }}
        shell: bash
        run: ../../../vendor/bin/phpunit --testdox --testsuite unit
